version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env.development  # This line ensures the frontend uses the development environment variables
    networks:
      - app-network

  backend:
    build:
      context: ./splitwise_backend
      dockerfile: Dockerfile
    env_file:
      - ./splitwise_backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
